version: "3.9"

services:
  test-db:
    image: postgres
    container_name: test_db
    environment:
      POSTGRES_DB: ${TEST_DB_NAME}
      POSTGRES_USER: ${TEST_DB_USERNAME}
      POSTGRES_PASSWORD: ${TEST_DB_PASSWORD}
    ports:
      - "${TEST_DB_PORT}:5432"
    volumes:
      - test_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${TEST_DB_USERNAME} -d ${TEST_DB_NAME}"]
      interval: 5s
      retries: 5

volumes:
  test_db_data:
